version: '3'

services:

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_nginx
    volumes:
      - .:/var/www/${PROJECT_NAME}/site
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
    networks:
      - common
    ports:
      - ${PROJECT_PORT}:80

  php-fpm:
    build: ./docker/php-fpm
    image: ${PROJECT_NAME}_php-fpm
    container_name: ${PROJECT_NAME}_php-fpm
    restart: unless-stopped
    working_dir: /var/www/${PROJECT_NAME}/site
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./docker/php-fpm/php.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      - ./docker/php-fpm/php-fpm.conf:/etc/php/8.1/fpm/pool.d/z-overrides.conf
      - ./docker/php-fpm/log:/var/log/php-fpm
      - .:/var/www/${PROJECT_NAME}/site
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    networks:
      - common

  mysql:
    image: mysql:8
    container_name: ${PROJECT_NAME}_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${PROJECT_NAME}
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/99-overrides.cnf
      - ./docker/mysql/db:/var/lib/mysql
      - ./docker/mysql/bak/:/bak
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - common

networks:
  common:
    external: true
